# Goal -  build the image for devboard frontent and push to docker

name: CI

on: 
  push:
    branches: [master]

jobs:
  code-lint:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v7
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Change to your Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      # Step 4: Run ESLint
      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx
          
  build-and-push-code:
    needs: [code-lint]
    runs-on: ubuntu-latest

    steps:
      - name: checkout the code
        uses: actions/checkout@v7

      - name: Login to docker hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build and push image
        uses: docker/build-push-action@v7
        with:
          context: ./frontend
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/devboard-fe-master:latest
        
